### ISSUE TITLE
Rework downloads page

### ISSUE THREAD

**Issue by phit** [Minecrell/SpongeDownloads#9]
Adding to https://github.com/SpongePowered/SpongeDownloads/issues/8

Downloads page should be removing the highlight on Latest Build and instead show Recommended Build at the top, hiding all other versions in a spoiler like the [Forge site](http://files.minecraftforge.net/) does.

Stable should be renamed to Release, as it doesn't imply stability. Recommended Build will be instead the stable version.

Something like this:
![](https://i.imgur.com/2Yc5AbS.png)

**Comment by stephan-gh** [comment]
Agreed. One part of this exists already: The latest build is only highlighted if no recommended build is available (can see that on the API for example).

**Comment by stephan-gh** [comment]
Actually, this issue should be on SpongeHome, SpongeDownloads is only the backend. Can you re-open this issue there?

**Comment by phit** [comment]
sure
